Exercice 1:

In [88]:
import numpy as np
def plus_longue_ss_suite_comm(X,Y):
    Z=list()
    m=len(X)
    n=len(Y)
    c=np.zeros((m+1,n+1))
    b=np.zeros((m+1,n+1))
    for i in range(m):
        c[i,0]=0
    for j in range(n):
        c[0,j]=0
    for i in range(m):
        for j in range(n):
            if(X[i]==Y[j]):
                c[i+1,j+1]=c[i,j]+1
                b[i+1,j+1]=1# 1 signifie que le prédecesseur est la case en haut à gauche
            else:
                if c[i,j+1]>= c[i+1,j]:
                    c[i+1,j+1]=c[i,j+1]
                    b[i+1,j+1]=2 # 2 : le prédecesseur est la case du dessus
                else:
                    c[i+1,j+1]=c[i+1,j]
                    b[i+1,j+1]=3 # le préd est la case de gauche
    i=m
    j=n# on part en bas à droite de la matrice
    while(b[i,j]!=0):# tant qu'on n'est pas arrivé sur la première colonne ou ligne, 
        #on parcourt les prédecesseurs et on les ajoute à Z si ils correspondent à un délacement diagonal  
        if b[i,j]==2:
            i-=1
        elif b[i,j]==1:
            i-=1
            j-=1
            Z.append(X[i])
        else:
            j-=1 
    return c,Z[::-1]            

In [93]:
plus_longue_ss_suite_comm(['A','B','C','B','D','A','B'],['B','D','C','A','B','A'])

(array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  1.,  1.,  1.],
        [ 0.,  1.,  1.,  1.,  1.,  2.,  2.],
        [ 0.,  1.,  1.,  2.,  2.,  2.,  2.],
        [ 0.,  1.,  1.,  2.,  2.,  3.,  3.],
        [ 0.,  1.,  2.,  2.,  2.,  3.,  3.],
        [ 0.,  1.,  2.,  2.,  3.,  3.,  4.],
        [ 0.,  1.,  2.,  2.,  3.,  4.,  4.]]), ['B', 'C', 'B', 'A'])

Exercice 2:

In [91]:
plus_longue_ss_suite_comm([0,1,0,1,1,0,1,1,0],[1,0,0,1,0,1,0,1])

(array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 0.,  1.,  1.,  1.,  2.,  2.,  2.,  2.,  2.],
        [ 0.,  1.,  2.,  2.,  2.,  3.,  3.,  3.,  3.],
        [ 0.,  1.,  2.,  2.,  3.,  3.,  4.,  4.,  4.],
        [ 0.,  1.,  2.,  2.,  3.,  3.,  4.,  4.,  5.],
        [ 0.,  1.,  2.,  3.,  3.,  4.,  4.,  5.,  5.],
        [ 0.,  1.,  2.,  3.,  4.,  4.,  5.,  5.,  6.],
        [ 0.,  1.,  2.,  3.,  4.,  4.,  5.,  5.,  6.],
        [ 0.,  1.,  2.,  3.,  4.,  5.,  5.,  6.,  6.]]), [0, 1, 0, 1, 0, 1])

Exercice 3

In [96]:
def plus_longue_ss_suite_croissante(X):
    return plus_longue_ss_suite_comm(X,sorted(X))


In [97]:
plus_longue_ss_suite_croissante([0,6,2,8,4,5,1,2,9])

(array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 0.,  1.,  1.,  1.,  1.,  1.,  1.,  2.,  2.,  2.],
        [ 0.,  1.,  1.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
        [ 0.,  1.,  1.,  2.,  2.,  2.,  2.,  2.,  3.,  3.],
        [ 0.,  1.,  1.,  2.,  2.,  3.,  3.,  3.,  3.,  3.],
        [ 0.,  1.,  1.,  2.,  2.,  3.,  4.,  4.,  4.,  4.],
        [ 0.,  1.,  2.,  2.,  2.,  3.,  4.,  4.,  4.,  4.],
        [ 0.,  1.,  2.,  3.,  3.,  3.,  4.,  4.,  4.,  4.],
        [ 0.,  1.,  2.,  3.,  3.,  3.,  4.,  4.,  4.,  5.]]), [0, 2, 4, 5, 9])

Exercice 4:

In [142]:
nbre_cube=[i**3 for i in range(30)]
nbre_pyramide=np.cumsum([i**2 for i in range(90)])
list_of_lists = [nbre_pyramide,nbre_cube]
flattened_list = [y for x in list_of_lists for y in x]
list_cube_pyramide=sorted(np.unique(flattened_list))

In [143]:
list_cube_pyramide

[0,
 1,
 5,
 8,
 14,
 27,
 30,
 55,
 64,
 91,
 125,
 140,
 204,
 216,
 285,
 343,
 385,
 506,
 512,
 650,
 729,
 819,
 1000,
 1015,
 1240,
 1331,
 1496,
 1728,
 1785,
 2109,
 2197,
 2470,
 2744,
 2870,
 3311,
 3375,
 3795,
 4096,
 4324,
 4900,
 4913,
 5525,
 5832,
 6201,
 6859,
 6930,
 7714,
 8000,
 8555,
 9261,
 9455,
 10416,
 10648,
 11440,
 12167,
 12529,
 13685,
 13824,
 14910,
 15625,
 16206,
 17575,
 17576,
 19019,
 19683,
 20540,
 21952,
 22140,
 23821,
 24389,
 25585,
 27434,
 29370,
 31395,
 33511,
 35720,
 38024,
 40425,
 42925,
 45526,
 48230,
 51039,
 53955,
 56980,
 60116,
 63365,
 66729,
 70210,
 73810,
 77531,
 81375,
 85344,
 89440,
 93665,
 98021,
 102510,
 107134,
 111895,
 116795,
 121836,
 127020,
 132349,
 137825,
 143450,
 149226,
 155155,
 161239,
 167480,
 173880,
 180441,
 187165,
 194054,
 201110,
 208335,
 215731,
 223300,
 231044,
 238965]

[0,
 1,
 5,
 8,
 14,
 27,
 30,
 55,
 64,
 91,
 125,
 140,
 204,
 216,
 285,
 343,
 385,
 506,
 512,
 650,
 729,
 819,
 1000,
 1015,
 1240,
 1331,
 1496,
 1728,
 1785,
 2109,
 2197,
 2470,
 2744,
 3375,
 4096,
 4913,
 5832,
 6859]